[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/finiscontiral/astro-data-vault"
description = "Astro Data Vault"
readme = "README.md"

[workspace.dependencies]
bytes = { version = "1.12.1", features = ["serde"] }
chrono = { version = "0.4.45", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
